name: Weekly Night Scan

on:
  schedule:
    # Твой Cron: воскресенье в 22:30
    - cron: '30 22 * * 0'
  workflow_dispatch:

jobs:
  scheduled-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run scheduled tests
        run: pytest -v